// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Token {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub symbol: ::prost::alloc::string::String,
    #[prost(int32, tag="4")]
    pub decimals: i32,
    #[prost(string, optional, tag="5")]
    pub last_price_usd: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="6")]
    pub last_price_block_number: ::core::option::Option<::prost::alloc::string::String>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VaultFee {
    /// "{feeType}-{vault}"
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    /// Percentage, e.g. "0.1" means 0.1%.
    #[prost(string, optional, tag="2")]
    pub fee_percentage: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, tag="3")]
    pub fee_type: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct YieldAggregator {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub slug: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub schema_version: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub subgraph_version: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub methodology_version: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub network: ::prost::alloc::string::String,
    #[prost(string, tag="8")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(string, tag="9")]
    pub total_value_locked_usd: ::prost::alloc::string::String,
    #[prost(string, optional, tag="10")]
    pub protocol_controlled_value_usd: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, tag="11")]
    pub cumulative_supply_side_revenue_usd: ::prost::alloc::string::String,
    #[prost(string, tag="12")]
    pub cumulative_protocol_side_revenue_usd: ::prost::alloc::string::String,
    #[prost(string, tag="13")]
    pub cumulative_total_revenue_usd: ::prost::alloc::string::String,
    #[prost(int32, tag="14")]
    pub cumulative_unique_users: i32,
    #[prost(int32, tag="15")]
    pub total_pool_count: i32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Vault {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub protocol: ::prost::alloc::string::String,
    #[prost(string, optional, tag="3")]
    pub name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="4")]
    pub symbol: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, tag="5")]
    pub input_token: ::prost::alloc::string::String,
    #[prost(string, optional, tag="6")]
    pub output_token: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, repeated, tag="7")]
    pub reward_tokens: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag="8")]
    pub deposit_limit: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="9")]
    pub fees: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag="10")]
    pub created_timestamp: ::prost::alloc::string::String,
    #[prost(string, tag="11")]
    pub created_block_number: ::prost::alloc::string::String,
    #[prost(string, tag="12")]
    pub total_value_locked_usd: ::prost::alloc::string::String,
    #[prost(string, tag="13")]
    pub cumulative_supply_side_revenue_usd: ::prost::alloc::string::String,
    #[prost(string, tag="14")]
    pub cumulative_protocol_side_revenue_usd: ::prost::alloc::string::String,
    #[prost(string, tag="15")]
    pub cumulative_total_revenue_usd: ::prost::alloc::string::String,
    #[prost(string, tag="16")]
    pub input_token_balance: ::prost::alloc::string::String,
    #[prost(string, optional, tag="17")]
    pub output_token_supply: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="18")]
    pub output_token_price_usd: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="19")]
    pub price_per_share: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="20")]
    pub staked_output_token_amount: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, repeated, tag="21")]
    pub reward_token_emissions_amount: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag="22")]
    pub reward_token_emissions_usd: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Deposit {
    /// "{hash}-{logIndex}"
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub hash: ::prost::alloc::string::String,
    #[prost(int32, tag="3")]
    pub log_index: i32,
    #[prost(string, tag="4")]
    pub protocol: ::prost::alloc::string::String,
    /// The vault.
    #[prost(string, tag="5")]
    pub to: ::prost::alloc::string::String,
    /// The address that supplied the assets.
    #[prost(string, tag="6")]
    pub from: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub block_number: ::prost::alloc::string::String,
    #[prost(string, tag="8")]
    pub timestamp: ::prost::alloc::string::String,
    #[prost(string, tag="9")]
    pub asset: ::prost::alloc::string::String,
    #[prost(string, tag="10")]
    pub amount: ::prost::alloc::string::String,
    #[prost(string, tag="11")]
    pub amount_usd: ::prost::alloc::string::String,
    #[prost(string, tag="12")]
    pub vault: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Withdraw {
    /// "{hash}-{logIndex}"
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub hash: ::prost::alloc::string::String,
    #[prost(int32, tag="3")]
    pub log_index: i32,
    #[prost(string, tag="4")]
    pub protocol: ::prost::alloc::string::String,
    /// The address that received the assets.
    #[prost(string, tag="5")]
    pub to: ::prost::alloc::string::String,
    /// The vault.
    #[prost(string, tag="6")]
    pub from: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub block_number: ::prost::alloc::string::String,
    #[prost(string, tag="8")]
    pub timestamp: ::prost::alloc::string::String,
    #[prost(string, tag="9")]
    pub asset: ::prost::alloc::string::String,
    #[prost(string, tag="10")]
    pub amount: ::prost::alloc::string::String,
    #[prost(string, tag="11")]
    pub amount_usd: ::prost::alloc::string::String,
    #[prost(string, tag="12")]
    pub vault: ::prost::alloc::string::String,
}
/// Everything that changed in one block. Entities are full upserts: a sink
/// writes each one over the previous row with the same id.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Entities {
    #[prost(uint64, tag="1")]
    pub block_number: u64,
    #[prost(string, tag="2")]
    pub block_hash: ::prost::alloc::string::String,
    #[prost(int64, tag="3")]
    pub timestamp: i64,
    #[prost(message, optional, tag="4")]
    pub protocol: ::core::option::Option<YieldAggregator>,
    #[prost(message, repeated, tag="5")]
    pub tokens: ::prost::alloc::vec::Vec<Token>,
    #[prost(message, repeated, tag="6")]
    pub vault_fees: ::prost::alloc::vec::Vec<VaultFee>,
    #[prost(message, repeated, tag="7")]
    pub vaults: ::prost::alloc::vec::Vec<Vault>,
    #[prost(message, repeated, tag="8")]
    pub deposits: ::prost::alloc::vec::Vec<Deposit>,
    #[prost(message, repeated, tag="9")]
    pub withdraws: ::prost::alloc::vec::Vec<Withdraw>,
}
// @@protoc_insertion_point(module)
