// @generated
// This file is @generated by prost-build.
/// One Deposit or Withdraw log, lifted out of Pinax's per-transaction shape
/// and stamped with block context, which the upstream output does not carry.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Flow {
    #[prost(enumeration="FlowKind", tag="1")]
    pub kind: i32,
    #[prost(string, tag="2")]
    pub vault: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub sender: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub owner: ::prost::alloc::string::String,
    /// Withdraw only.
    #[prost(string, tag="5")]
    pub receiver: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub assets: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub shares: ::prost::alloc::string::String,
    #[prost(string, tag="8")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(string, tag="9")]
    pub tx_from: ::prost::alloc::string::String,
    #[prost(uint32, tag="10")]
    pub log_index: u32,
    #[prost(uint64, tag="11")]
    pub ordinal: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Flows {
    #[prost(uint64, tag="1")]
    pub block_number: u64,
    #[prost(string, tag="2")]
    pub block_hash: ::prost::alloc::string::String,
    #[prost(int64, tag="3")]
    pub timestamp: i64,
    #[prost(message, repeated, tag="4")]
    pub flows: ::prost::alloc::vec::Vec<Flow>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Token {
    #[prost(string, tag="1")]
    pub address: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub symbol: ::prost::alloc::string::String,
    #[prost(uint32, tag="4")]
    pub decimals: u32,
    /// False when decimals() reverted; decimals then defaults to 18.
    #[prost(bool, tag="5")]
    pub decimals_ok: bool,
}
/// Registry entry, resolved by eth_call exactly once per address.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VaultInfo {
    #[prost(string, tag="1")]
    pub address: ::prost::alloc::string::String,
    /// Vault share token metadata.
    #[prost(message, optional, tag="2")]
    pub share: ::core::option::Option<Token>,
    /// Underlying asset from asset().
    #[prost(message, optional, tag="3")]
    pub asset: ::core::option::Option<Token>,
    #[prost(bool, tag="4")]
    pub asset_probe_ok: bool,
    #[prost(uint64, tag="5")]
    pub first_seen_block: u64,
    #[prost(int64, tag="6")]
    pub first_seen_timestamp: i64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VaultInfos {
    #[prost(message, repeated, tag="1")]
    pub vaults: ::prost::alloc::vec::Vec<VaultInfo>,
}
/// One vault's state at the end of one block in which it had flows. This is
/// the series the attestation service reads: everything needed to state
/// "vault X held Y of asset Z at block N / time T" in a single message.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VaultBlock {
    #[prost(string, tag="1")]
    pub vault: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub asset: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub asset_symbol: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub share_symbol: ::prost::alloc::string::String,
    #[prost(enumeration="Verification", tag="5")]
    pub verification: i32,
    #[prost(uint32, tag="6")]
    pub share_decimals: u32,
    #[prost(uint32, tag="7")]
    pub asset_decimals: u32,
    #[prost(uint64, tag="10")]
    pub block_number: u64,
    #[prost(string, tag="11")]
    pub block_hash: ::prost::alloc::string::String,
    #[prost(int64, tag="12")]
    pub timestamp: i64,
    /// Raw sums over this block's flows.
    #[prost(string, tag="20")]
    pub deposit_assets: ::prost::alloc::string::String,
    #[prost(string, tag="21")]
    pub deposit_shares: ::prost::alloc::string::String,
    #[prost(string, tag="22")]
    pub withdraw_assets: ::prost::alloc::string::String,
    #[prost(string, tag="23")]
    pub withdraw_shares: ::prost::alloc::string::String,
    #[prost(uint32, tag="24")]
    pub deposit_count: u32,
    #[prost(uint32, tag="25")]
    pub withdraw_count: u32,
    /// Normalised sums and signed net flow (deposits minus withdrawals).
    #[prost(string, tag="30")]
    pub deposit_assets_norm: ::prost::alloc::string::String,
    #[prost(string, tag="31")]
    pub deposit_shares_norm: ::prost::alloc::string::String,
    #[prost(string, tag="32")]
    pub withdraw_assets_norm: ::prost::alloc::string::String,
    #[prost(string, tag="33")]
    pub withdraw_shares_norm: ::prost::alloc::string::String,
    #[prost(string, tag="34")]
    pub net_assets_norm: ::prost::alloc::string::String,
    #[prost(string, tag="35")]
    pub net_shares_norm: ::prost::alloc::string::String,
    /// Assets per share, normalised, volume-weighted over the block. Kept apart
    /// on purpose: Deposit.assets is gross of any entry fee and Withdraw.assets
    /// is net of any exit fee, so entry >= true price >= exit, and a blended
    /// number would hide the fee. Empty when the block had no flow of that kind.
    #[prost(string, tag="40")]
    pub entry_rate: ::prost::alloc::string::String,
    #[prost(string, tag="41")]
    pub exit_rate: ::prost::alloc::string::String,
    /// (entry - exit) / exit in basis points, only when both sides traded in
    /// the same block. Rounding makes this a few hundredths of a bp on fee-less
    /// vaults; anything larger is a fee.
    #[prost(string, tag="42")]
    pub fee_spread_bps: ::prost::alloc::string::String,
    /// entry_rate and exit_rate measured against state_price, as percentages.
    /// Premium > 0 means depositors paid above the end-of-block price; discount
    /// > 0 means withdrawers received below it. Both are fee plus rounding plus
    /// any interest accrued later in the same block.
    #[prost(string, tag="43")]
    pub entry_premium_pct: ::prost::alloc::string::String,
    #[prost(string, tag="44")]
    pub exit_discount_pct: ::prost::alloc::string::String,
    /// False when either rate sits outside \[-0.01%, +10%\] of state_price. A
    /// conforming vault cannot mint shares below its own price, and no
    /// disclosed ERC-4626 fee is above 10%. Contracts that pass the asset()
    /// probe but emit Deposit/Withdraw with other semantics (queued exits,
    /// rebasing receipts, LP tokens) land here. They keep their TVL but get no
    /// fee revenue, and a consumer acting on the price should refuse.
    #[prost(bool, tag="45")]
    pub rates_consistent: bool,
    /// End-of-block vault state from an eth_call pinned to this block's hash.
    #[prost(bool, tag="50")]
    pub state_ok: bool,
    #[prost(string, tag="51")]
    pub total_assets: ::prost::alloc::string::String,
    #[prost(string, tag="52")]
    pub total_supply: ::prost::alloc::string::String,
    #[prost(string, tag="53")]
    pub total_assets_norm: ::prost::alloc::string::String,
    #[prost(string, tag="54")]
    pub total_supply_norm: ::prost::alloc::string::String,
    /// total_assets_norm / total_supply_norm. Differs from convertToAssets() by
    /// the virtual-share offset, which is negligible once a vault has any size.
    #[prost(string, tag="55")]
    pub state_price: ::prost::alloc::string::String,
    /// maxDeposit(address(0)): the vault's deposit cap as seen by a fresh account.
    #[prost(string, tag="56")]
    pub max_deposit: ::prost::alloc::string::String,
    /// USD price of one unit of the underlying, empty when the asset is not in
    /// the pricing table. See README for how it is sourced.
    #[prost(string, tag="60")]
    pub asset_price_usd: ::prost::alloc::string::String,
    #[prost(string, tag="61")]
    pub tvl_usd: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VaultBlocks {
    #[prost(uint64, tag="1")]
    pub block_number: u64,
    #[prost(string, tag="2")]
    pub block_hash: ::prost::alloc::string::String,
    #[prost(int64, tag="3")]
    pub timestamp: i64,
    #[prost(message, repeated, tag="4")]
    pub vaults: ::prost::alloc::vec::Vec<VaultBlock>,
}
/// One nominated position, read by eth_call at this block: what the holder
/// actually has in the vault, and what the vault itself says that is worth.
/// These are exactly the inputs a coverage attestation needs.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Position {
    /// Label from the module params, normally the note's on-chain id.
    #[prost(string, tag="1")]
    pub note: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub holder: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub vault: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub asset: ::prost::alloc::string::String,
    #[prost(uint32, tag="5")]
    pub asset_decimals: u32,
    #[prost(uint32, tag="6")]
    pub share_decimals: u32,
    /// balanceOf(holder) on the vault.
    #[prost(string, tag="7")]
    pub shares: ::prost::alloc::string::String,
    /// convertToAssets(shares): the vault's own valuation, rounded down.
    #[prost(string, tag="8")]
    pub assets: ::prost::alloc::string::String,
    #[prost(string, tag="9")]
    pub assets_norm: ::prost::alloc::string::String,
    /// USD per unit of the asset and the position's USD value. Empty when the
    /// asset is unpriced. The block that price was last observed at is
    /// price_block.
    #[prost(string, tag="10")]
    pub asset_price_usd: ::prost::alloc::string::String,
    #[prost(string, tag="11")]
    pub value_usd: ::prost::alloc::string::String,
    #[prost(uint64, tag="12")]
    pub price_block: u64,
    /// False when balanceOf, asset(), decimals() or convertToAssets() reverted.
    /// The amounts are then empty, never zero: a zero would read as a finding.
    #[prost(bool, tag="13")]
    pub ok: bool,
    /// Registry verdict on the vault. VERIFICATION_UNSPECIFIED means this stream
    /// has not seen a flow on it since its initial block.
    #[prost(enumeration="Verification", tag="14")]
    pub verification: i32,
    /// rates_consistent from the vault's last block with flows, and that block.
    /// last_flow_block is 0 when no flow has been seen.
    #[prost(bool, tag="15")]
    pub rates_consistent: bool,
    #[prost(uint64, tag="16")]
    pub last_flow_block: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Positions {
    #[prost(uint64, tag="1")]
    pub block_number: u64,
    #[prost(string, tag="2")]
    pub block_hash: ::prost::alloc::string::String,
    #[prost(int64, tag="3")]
    pub timestamp: i64,
    /// True when positions were read at this block, either on a cadence tick or
    /// because a nominated vault had flows.
    #[prost(bool, tag="4")]
    pub positions_read: bool,
    #[prost(message, repeated, tag="5")]
    pub positions: ::prost::alloc::vec::Vec<Position>,
    /// map_vault_blocks for the same block, carried through so that a single
    /// stream can answer both vault and note questions.
    #[prost(message, repeated, tag="6")]
    pub vaults: ::prost::alloc::vec::Vec<VaultBlock>,
}
// Addresses are lowercase 0x-hex strings and token amounts are base-10
// strings of the raw uint256 (wei). Fields ending in `_norm` are divided by
// the relevant token's decimals and rendered as decimal strings, so a
// consumer never has to know which of the two tokens a number is in.

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum FlowKind {
    Unspecified = 0,
    Deposit = 1,
    Withdraw = 2,
}
impl FlowKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            FlowKind::Unspecified => "FLOW_KIND_UNSPECIFIED",
            FlowKind::Deposit => "FLOW_KIND_DEPOSIT",
            FlowKind::Withdraw => "FLOW_KIND_WITHDRAW",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "FLOW_KIND_UNSPECIFIED" => Some(Self::Unspecified),
            "FLOW_KIND_DEPOSIT" => Some(Self::Deposit),
            "FLOW_KIND_WITHDRAW" => Some(Self::Withdraw),
            _ => None,
        }
    }
}
/// How much we trust that an address is a real ERC-4626 vault. Pinax matches
/// on topic0 alone, so a non-4626 contract with a same-signature event passes
/// their filter.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Verification {
    Unspecified = 0,
    /// asset() reverted or returned something that is not an address with
    /// ERC-20 decimals. Excluded from every derived output.
    Rejected = 1,
    /// asset() resolved but only one of Deposit / Withdraw has been seen so far.
    AssetProbe = 2,
    /// asset() resolved and both event signatures have co-occurred on the address.
    Confirmed = 3,
}
impl Verification {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Verification::Unspecified => "VERIFICATION_UNSPECIFIED",
            Verification::Rejected => "VERIFICATION_REJECTED",
            Verification::AssetProbe => "VERIFICATION_ASSET_PROBE",
            Verification::Confirmed => "VERIFICATION_CONFIRMED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "VERIFICATION_UNSPECIFIED" => Some(Self::Unspecified),
            "VERIFICATION_REJECTED" => Some(Self::Rejected),
            "VERIFICATION_ASSET_PROBE" => Some(Self::AssetProbe),
            "VERIFICATION_CONFIRMED" => Some(Self::Confirmed),
            _ => None,
        }
    }
}
// @@protoc_insertion_point(module)
