import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import {
  BASE_CHAIN_ID,
  CONTROL_FIRST,
  HOLDER,
  NAMED_POSITION,
  PLAN,
  PLANNED_FUNDING_USDC,
  TOKENS,
  VAULTS,
  vaultByKey,
  type Market,
} from "./config.js";
import { noteIdOf, vaultSetHash } from "./liabilities.js";

/**
 * Writes the backing plan as JSON, so nothing else has to restate it.
 *
 * `src/config.ts` is the source of truth and it is TypeScript, which the web
 * app cannot import. Rather than let the app keep a hand-copied mirror of the
 * vault addresses — the one place a number would live in two files — this emits
 * the same values as a checked-in artifact for it to read.
 *
 * What is deliberately NOT here: outstanding supply, par, the threshold and the
 * holder's positions. Those are read from the chain at the time of use. This
 * file carries only what the chain cannot say — which vaults are nominated and
 * how much the issuer intends to put in each.
 */

export interface PlanArtifactLeg {
  readonly key: string;
  readonly name: string;
  readonly protocol: string;
  readonly address: string;
  readonly asset: string;
  /** Planned deposit in the asset's units, or "rest" for whatever remains. */
  readonly planned: number | "rest";
  /** Bounds on the "rest" leg, so the named position stays decisive. */
  readonly min?: number;
  readonly max?: number;
}

export interface PlanArtifactNote {
  readonly market: string;
  readonly noteId: string;
  readonly vaultSetHash: string;
  readonly negativeControl: boolean;
  /** Lowercase and sorted: the preimage of `vaultSetHash`. */
  readonly vaults: readonly string[];
  readonly legs: readonly PlanArtifactLeg[];
}

export interface PlanArtifact {
  readonly $comment: string;
  readonly generatedBy: string;
  readonly network: { readonly name: string; readonly chainId: number };
  readonly holder: string;
  readonly unit: { readonly symbol: string; readonly address: string; readonly decimals: number };
  readonly namedPosition: string;
  readonly plannedFundingUsdc: string;
  /** Markets in allocation order: the control is funded before the live note. */
  readonly allocationOrder: readonly string[];
  readonly notes: Record<string, PlanArtifactNote>;
}

export function buildPlanArtifact(): PlanArtifact {
  const notes: Record<string, PlanArtifactNote> = {};
  for (const market of Object.keys(PLAN) as Market[]) {
    const legs = PLAN[market].map((leg): PlanArtifactLeg => {
      const vault = vaultByKey(leg.vault);
      return {
        key: vault.key,
        name: vault.name,
        protocol: vault.protocol,
        address: vault.address,
        asset: vault.asset,
        planned: leg.amount === "rest" ? "rest" : Number(leg.amount),
        ...(leg.min === undefined ? {} : { min: Number(leg.min) }),
        ...(leg.max === undefined ? {} : { max: Number(leg.max) }),
      };
    });
    const vaults = VAULTS.filter((v) => v.market === market)
      .map((v) => v.address.toLowerCase())
      .sort();
    notes[market] = {
      market,
      noteId: noteIdOf(market),
      vaultSetHash: vaultSetHash(vaults),
      negativeControl: market === "PLIM-A",
      vaults,
      legs,
    };
  }

  return {
    $comment:
      "Generated by packages/backing (npm run plan). The source of truth is packages/backing/src/config.ts. " +
      "Outstanding supply, par, the load line and the holder's positions are absent on purpose: they are read " +
      "from the chain at the time of use, never configured.",
    generatedBy: "packages/backing",
    network: { name: "base", chainId: BASE_CHAIN_ID },
    holder: HOLDER,
    unit: { symbol: "USDC", address: TOKENS.USDC.address, decimals: TOKENS.USDC.decimals },
    namedPosition: NAMED_POSITION,
    plannedFundingUsdc: PLANNED_FUNDING_USDC,
    allocationOrder: [...CONTROL_FIRST],
    notes,
  };
}

const OUTPUT = fileURLToPath(new URL("../../backing-plan.json", import.meta.url));

export function writePlanArtifact(path = OUTPUT): string {
  writeFileSync(path, `${JSON.stringify(buildPlanArtifact(), null, 2)}\n`, "utf8");
  return path;
}

if (process.argv[1] && import.meta.url === new URL(`file://${process.argv[1].replace(/\\/g, "/")}`).href) {
  console.log(`wrote ${writePlanArtifact()}`);
}
