/**
 * Regenerate the device-signed fixture embedded in `test-sol/MandateVerifier.t.sol`.
 *
 * The Solidity suite verifies a signature that a Ledger actually produced, not one `vm.sign`
 * made up. Ledger signs with RFC 6979 deterministic nonces, so the same mandate and the same
 * seed always yield the same 65 bytes -- which is what makes it safe to bake into a test.
 *
 * Run with the emulator up: `npm run build && node dist/demo/fixture.js`
 */

import { DeviceAuthority } from "../src/device";
import { formatMandate, hashMandate } from "../src/mandate";
import { SpeculosScreen } from "../src/screen";
import { ensureIdle } from "../test/harness";
import { GOLDEN_MANDATE } from "../test/vectors";

async function main(): Promise<void> {
  const screen = new SpeculosScreen();
  await ensureIdle(screen);

  const device = DeviceAuthority.fromEnv();
  try {
    const pending = device.signMandate(GOLDEN_MANDATE);
    await new Promise((resolve) => setTimeout(resolve, 1_500));
    const walk = await screen.approve();
    if (!walk.found) throw new Error("never reached the sign screen");

    const result = await pending;
    if (!result.ok) throw new Error(`device did not sign: ${result.reason} ${result.detail}`);

    const text = formatMandate(GOLDEN_MANDATE);
    process.stdout.write(
      [
        "// generated by demo/fixture.ts against Speculos + app-ethereum 1.22.3",
        `bytes constant DEVICE_SIGNATURE = hex"${result.attestation.signature.slice(2)}";`,
        `// r = ${result.attestation.rsv.r}`,
        `// s = ${result.attestation.rsv.s}`,
        `// v = ${result.attestation.rsv.v}`,
        `// digest  = ${hashMandate(GOLDEN_MANDATE)}`,
        `// signer  = ${result.attestation.authority}`,
        `// message = ${JSON.stringify(text)}`,
        "",
      ].join("\n"),
    );
  } finally {
    await device.close();
    await ensureIdle(screen).catch(() => undefined);
  }
}

main().catch((error) => {
  process.exitCode = 1;
  process.stderr.write(`${(error as Error).message}\n`);
});
